Fixing the Bounding Rectangle Selection on reload
agentcooper/react-pdf-highlighter pull request #100
Opened 2020-12-11 21:23 UTC by jinman

Thanks to @JAlvezzz, I am merging his changes after testing and creating PR.

2020-12-12 18:01 UTC, agentcooper requested changes
Could you also please use Prettier to format? CI shows incorrect formatting as an error.

2020-12-15 08:06 UTC, jinman commented on packages/react-pdf-highlighter/src/components/MouseSelection.js
> +        y: pageY - realContainerBoundingRect.top + container.scrollTop
I tried and it works that but was not sure whether I missing some test cases. So I reverted back to @JALvezzz's checkin assuming that he has done more comprehensive testing. Anyway, I checkedin with the fix as per your recommendation.

2020-12-29 03:29 UTC, jinman commented
@agentcooper can we approve this change for the main build. Does this work? Thank you!

2021-01-07 05:41 UTC, jinman commented
@agentcooper Any idea this can be merged?

2021-01-10 18:48 UTC, merged

2021-01-10 18:48 UTC, agentcooper commented
Thanks!

2021-01-20 08:17 UTC, jinman commented
@agentcooper do you know when will this released and merged in npm v3.3.1 ?

2021-02-08 15:33 UTC, agentcooper commented
Published in 3.4.0.